sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm i -g npm@^6.0.0
before_script:
  - npm prune
  - nvm install 12.1.0
script:
  - npm run test:single
after_success:
  - npm run semantic-release