sudo: false
language: node_js
node_js:
  - 12
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run test:single
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run semantic-release